config/routes.rb
Rails.application.routes.draw do

  resources :trial_versions

  resources :accrual_disease_terms

  resources :trial_documents

  scope "/ctrp" do

    namespace "ws" do
      scope '/api' do
        scope '/v1' do
          scope '/trials' do
            scope '/complete' do
              get '/' => 'api_trials#index'
              get '/:id' =>  'api_trials#show'
              post '/' => 'api_trials#create'
              post '/:idType/:id' => 'api_trials#update'
              post '/:id' => 'api_trials#update'
              put '/:idType/:id' => 'api_trials#amend'
              put  '/:id' =>  'api_trials#update'
              put  '/:id/status' =>  'api_trials#change_status'
            end
          end
        end
      end
    end

    devise_for :users
    root 'ctrp#index'

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    get '/ctrp/', :to => redirect('/index.html')
    resources :organizations do
      collection do
        get 'search'
        post 'search'
        post 'select'
        post 'curate'
        post 'unique', defaults: {format: 'json'}
      end
    end

    resources :source_statuses

    resources :source_contexts

    resources :families do
      collection do
            get 'search'
            post 'search'
            post 'unique', defaults: {format: 'json'}
          end
    end

    resources :families do
      member do
        get  'get_orgs'
      end
      end

    scope '/familystuff' do

      resources :family_statuses, :family_types, :family_relationships, :family_memberships

    end

    resources :family_statuses

    resources :family_types

    resources :family_relationships

    resources :family_memberships

    resources :pa_trials
    get '/pa/trial/:trial_id/checkout/:type', to: 'trials#checkout_trial'
    get '/pa/trial/:trial_id/checkin/:type', to: 'trials#checkin_trial'

    resources :comments
    get '/instance/:uuid/comments/count(/:field)', to: 'comments#count'
    get '/instance/:uuid/comments(/:field)', to: 'comments#comments_for_instance'

    get '/users/search' => 'users#search'
    get '/users/gsa' => 'users#gsa'
    post '/users/search' => 'users#search'
    resources :users, param: :username do
      member do
        post 'approve'
        post 'disapprove'
      end
    end

    resources :people do
      collection do
        get 'search'
        post 'search'
        post 'curate'
        post 'unique', defaults: {format: 'json'}
      end
    end

    resources :trial_versions do
      collection do
        get 'index'
        post 'history'
      end
    end

    resources :po_affiliations
    resources :po_affiliation_statuses

    get '/countries' => 'util#get_countries'
    get '/states' => 'util#get_states'
    get '/backoffice' => 'backoffice#index'
    get '/backoffice/download_log'
    get '/backoffice/static_members'

    get '/dmzutils/app_version' => 'dmz_utils#get_app_version'
    get '/dmzutils/app_rel_milestone' => 'dmz_utils#get_app_rel_milestone'
    get '/dmzutils/login_bulletin' => 'dmz_utils#get_login_bulletin'
    get '/dmzutils/git_info' => 'dmz_utils#get_git_info'

    devise_scope :user do
      delete "sign_out" => "sessions#destroyrailslogin", :as => :destroyrailslogin_session
    end

    devise_for :ldap_users, :local_users, skip: [ :sessions ]
    devise_for :omniauth_users, :controllers => { :omniauth_callbacks => "omniauth_users/omniauth_callbacks" }
    devise_scope :local_user do
      get 'sign_in' => 'sessions#new', :as => :new_session
      post 'sign_in' => 'sessions#create', :as => :create_session
      post 'sign_out' => 'sessions#destroy', :as => :destroy_session
      post 'sign_up' => 'registrations#create', :as => :create_registration
      get 'change_password' => 'registrations#edit', :as => :edit_registration
      post 'change_password' => 'registrations#update', :as => :update_registration
    end

    scope '/pa' do
      get 'nih_nci_div_pa' => 'util#get_nih_nci_div_pa'
      get 'nih_nci_prog_pa' => 'util#get_nih_nci_prog_pa'
      get 'trial_document_types' => 'util#trial_document_types'
      resources :submission_methods
    end

    scope '/registry' do
      resources :study_sources
      resources :phases
      resources :primary_purposes
      resources :secondary_purposes
      resources :accrual_disease_terms
      resources :responsible_parties
      resources :trials do
        collection do
          get  'search'
          post 'search'
          get  'search_pa'
          post 'search_pa'
          post 'validate_status'
          get  'get_grants_serialnumber'
          post 'get_grants_serialnumber'
          get  'get_central_contact_types'
          get  'search_clinical_trials_gov'
          post 'import_clinical_trials_gov'
          get  'get_board_approval_statuses'
        end
      end

      resources :protocol_id_origins
      resources :holder_types
      resources :expanded_access_types
      resources :trial_statuses
      resources :processing_statuses
      resources :milestones
      resources :research_categories
      resources :site_recruitment_statuses
      resources :participating_sites do
        collection do
          post 'validate_status'
        end
      end
      resources :site_rec_status_wrappers
      resources :trial_documents do
        collection do
          get 'download/:id' => 'trial_documents#download'
        end
      end

      get 'funding_mechanisms' => 'util#get_funding_mechanisms'
      get 'institute_codes' => 'util#get_institute_codes'
      get 'nci' => 'util#get_nci'
      get 'nih' => 'util#get_nih'

      get 'accepted_file_types' => 'util#get_accepted_file_types'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, :only => :index
  #before_filter :wrapper_authenticate_user unless Rails.env.test?

  attr_accessor :gsa_text

  # GET /users
  # GET /users.json
  def index
    # The Current User logged in
    Rails.logger.info "@user = #{@user.inspect}"
    @users = []
    unless @user.blank?
      @users = @user.get_all_users_by_role
      #Rails.logger.info "UserController,index @users = #{@users.inspect}"
    end
  end

  def show
    @user = User.find_by_username(params[:username])
  end


  def update
    @user = User.find_by_username(params[:user][:username])
    Rails.logger.info "In Users Controller, update before user = #{@user.inspect}"

    respond_to do |format|
      #@person.po_affiliations.destroy
      if @user.update_attributes(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render json: @user}
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

    Rails.logger.info "In Users Controller, update after user = #{@user.inspect}"
  end

  def approve
    # When an ADMIN approves of the user request for privileges, the role is updated
    # if it is not already chosen and the approved field is set to true
    @user = User.find_by_username(params[:username])
    @user.process_approval
    redirect_to users_path

  end

  def disapprove
      # When an ADMIN disapproves of the user request for privileges, the role is set to nill
      # and the approved field is set to false
    @user = User.find_by_username(params[:username])
    @user.process_disapproval
    redirect_to users_path
  end

  def gsa

    yml_content = YAML.load_file(Rails.root.join('config', 'locales').to_s + '/en.yml')
    #Rails.logger.debug "yml_content = #{yml_content.inspect}"
    # It is critical to make sure that we dont loose the current_user when going through
    # the GSA Acceptance
    user = nil
    if @current_user.nil?
      @current_user = get_user
    end
    user = @current_user

    auth_string = request.headers['Authorization']
    if !auth_string.blank?
      Rails.logger.debug "UserController, GSA, auth_string = #{auth_string.inspect}"
      token = auth_string.split(" ")[1]
      Rails.logger.debug "UserController, GSA, auth_string = #{token.inspect}"
      user_id = decode_token(token)
      Rails.logger.debug "UserController, GSA, user_id = #{user_id.inspect}"
      user = User.find(user_id)
      @current_user = user
      Rails.logger.debug "UserController, GSA, user = #{user.username.inspect}" unless user.nil?
    end

    Rails.logger.debug "IN GSA @current_user = #{@current_user}"

    unless user.nil?
      authenticate_user(user)
      if user.is_a?(LocalUser)
        gsa_text = yml_content['en']['non_nih_user_gsa_msg']
      elsif user.is_a?(LdapUser)
        gsa_text = yml_content['en']['nih_user_gsa_msg']
      else
        gsa_text = yml_content['en']['non_nih_user_gsa_msg']
      end
    else
      gsa_text = yml_content['en']['non_nih_user_gsa_msg']
    end

    render :status => 200, :json => { :success => true, :gsa => "#{gsa_text}", :info => "GSA Msg"}

end


  def search
    Rails.logger.info "In User controller params = #{params.inspect}"
    # Pagination/sorting params initialization
    params[:start] = 1 if params[:start].blank?
    params[:rows] = 10 if params[:rows].blank?
    params[:sort] = 'username' if params[:sort].blank?
    params[:order] = 'asc' if params[:order].blank?
    @users = User.all

    if params[:username].present? || params[:first_name].present? || params[:last_name].present? || params[:email].present?
      @users = @users.select{|x| x.username && x.username.include?(params[:username])} if params[:username].present?
      @users = @users.select{|x| x.first_name && x.first_name.include?(params[:first_name])} if params[:first_name].present?
      @users = @users.select{|x| x.last_name && x.last_name.include?(params[:last_name])} if params[:last_name].present?
      @users = @users.select{|x| x.email && x.email.include?(params[:email])} if params[:email].present?
    end
    Rails.logger.info "In User controller, search @users = #{@users.inspect}"
    @users
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      unless params.nil? || params[:id].nil? || params[:username].nil?
        @user = User.find(params[:id]) || User.find(params[:username])
      else
        @user = current_user || current_local_user || current_ldap_user || current_omniauth_user
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :zipcode, :first_name, :last_name, :middle_name, :receive_email_notifications,  :updated_at, :created_at, :role, :street_address, :organization_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(:user, :url => user_path(@user)) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <p>
      <%= f.label :username %><br/>
      <%= f.text_field :username %>
    </p>

    <p>
      <%= f.label :email %><br/>
      <%= f.text_field :email %>
    </p>

    <p>
      <%= f.label :role %><br/>
      <%= f.text_field :role %>
    </p>


    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', :user, :url => user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/gsa.html.erb
<h1>GSA </h1>

<% if local_user_signed_in? %>

<p>
  <b>NCI CLINICAL TRIALS REPORTING PROGRAM (CTRP) SYSTEM </b>
  This is a U.S. Government computer system, which may be accessed and used only for authorized Government business by authorized personnel. Unauthorized access or use of this computer system may subject violators to criminal, civil, and/or administrative action.
  All information on this computer system may be intercepted, recorded, read, copied, and disclosed by and to authorized personnel for official purposes, including criminal investigations. Such information includes sensitive data encrypted to comply with confidentiality and privacy requirements. Access or use of this computer system by any person, whether authorized or unauthorized, constitutes consent to these terms. There is no right of privacy in this system. |


</p>

<% elsif ldap_user_signed_in?  %>

    <b>NCI CLINICAL TRIALS REPORTING PROGRAM (CTRP) SYSTEM </b>
    This is a U.S. Government computer system, which may be accessed and used only for authorized Government business by authorized personnel. Unauthorized access or use of this computer system may subject violators to criminal, civil, and/or administrative action.
    All information on this computer system may be intercepted, recorded, read, copied, and disclosed by and to authorized personnel for official purposes, including criminal investigations. Such information includes sensitive data encrypted to comply with confidentiality and privacy requirements. Access or use of this computer system by any person, whether authorized or unauthorized, constitutes consent to these terms. There is no right of privacy in this system.
    NOTIFICATION TO RESPONDENT OF ESTIMATED BURDEN
    OMB#: 0925-0600 EXP. DATE: 5/31/16
    Public reporting burden for this collection of information is estimated to average sixty (60) minutes for this questionnaire, including the time to review instructions, search existing data sources, gather and maintain the data needed, and complete and review the collection of information. An agency may not conduct or sponsor, and a person is not required to respond to, a collection of information unless it displays a current, valid OMB control number.
    Send comments regarding this burden estimate or any other aspect of this collection of information, including suggestions for reducing the burden to:  NIH, Project Clearance Branch, 6705 Rockledge Drive, MSC 7974, Bethesda, MD 20892-7974, ATTN: PRA (0925-0600).
    Do not return the completed form to this address. |

<% end %>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">

  <title>CTRP User Portal</title>
</head>
<body>


<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">CTRP User Portal</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">


        <% if local_user_signed_in? %><li><a class="navbar-brand" href="#">Current Local User is <%= current_local_user.username %></a><li/> <% end %>

            <li><%= link_to 'Sign out', destroy_session_path, method: :delete %></li>

      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2">
      <ul class="nav nav-stacked">
        <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
        <br/><br/>
        <li><a href="/ctrp/ui#/main/sign_in">CTRP Main</a></li>
        <% if local_user_signed_in? %>
            <% if current_local_user.approved? %>
                <li><%= link_to "List Users", users_path %></li>
                <% if current_local_user.role == "ROLE_SUPER"  && current_local_user.organization_id.nil? %>
                    <li><%= link_to "BackOffice", backoffice_path %></li>
                <% end %>
            <% end %>
            <li><%= link_to "Assign Organization", search_organizations_path %></li>
        <% end %>
        <% if ldap_user_signed_in? %>
            <% if current_ldap_user.approved? %>
                <li><%= link_to "List Users", users_path %></li>
                <% if current_ldap_user.role == "ROLE_SUPER" && current_ldap_user.organization_id.nil? %>
                    <li><%= link_to "BackOffice", backoffice_path %></li>
                <% end %>
            <% end %>
            <li><%= link_to "Assign Organization", search_organizations_path %></li>
        <% end %>
        <% if !local_user_signed_in? &&  !ldap_user_signed_in? %>
            <li><%= link_to "Sign In", new_session_path %></li>
            <li><a href="/ctrp/local_users/sign_up">Sign Up</a></li>
        <% end %>
        <% if local_user_signed_in? %>
            <li><%= link_to "Change your password", edit_registration_path %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-sm-9 col-md-10">
      <h3 class="header">
        <% if local_user_signed_in?  %>

            <b>Current User: <%= current_local_user.username %> </b>
            , Role: <%= current_local_user.role %>
            <% unless current_local_user.organization_id.blank? %>
                , Organization: <%= current_local_user.organization.name %>
            <% end %>
            <br/>
        <% end %>
        <% if  ldap_user_signed_in? %>

            <b>Current User: <%= current_ldap_user.username %> </b>
            , Role: <%= current_ldap_user.role %>
            <% unless current_ldap_user.organization_id.blank? %>
                , Organization: <%= current_ldap_user.organization.name %>
            <% end %>
            <br/>
        <% end %>
      </h3>

      <% unless @users.blank? %>
              <h3>List CTRP Users</h3>
          <div class="table-responsive">
            <table class="table table-bordered table-striped">
              <thead>
              <tr>
              <tr>
                <th colspan="2">Username</th>
                <th colspan="3">Type</th>
                <th colspan="3">Role</th>
                <th colspan="3">Privileges</th>
                <th colspan="3">Organization</th>
                <th colspan="*">Approval</th>
              </tr>
              </tr>
              </thead>
              <tbody>

              <% @users.each do |user| %>
                  <tr>
                    <td colspan="2"><%= user.username %></td>
                    <td colspan="3"><%= user.type %></td>
                    <td colspan="3"><%= user.role %></td>
                    <% unless user.organization_id.blank? %>
                        <td colspan="3" class="info"><%= user.organization.name %>&nbsp; </td>
                    <% else %>
                        <td colspan="3"> &nbsp; </td>
                    <% end %>
                    <% if user.approved == false %>
                        <td colspan="3">NOT APPROVED</td>
                      <td colspan="3">
                        <!--
                        <%= button_to [:approve, user.becomes(User)] do %>
                            <strong class="btn btn-sm btn-primary">Approve</strong>
                        <% end %>
                        -->

                        <%= form_tag [:approve, user.becomes(User)] do %>
                            <button class="btn btn-sm btn-primary" type="submit">Approve</button>
                        <% end %>
                      </td>
                    <% end %>
                    <% if user.approved == true %>
                        <td colspan="3">APPROVED</td>
                        <td colspan="3">
                            <!--
                            <%= button_to [:disapprove, user.becomes(User)] do %>
                                <strong class="btn btn-sm btn-danger">Disable</strong>
                            <% end %>
                            -->

                            <%= form_tag [:disapprove, user.becomes(User)] do %>
                                <button class="btn btn-sm btn-danger" type="submit">Disable</button>
                            <% end %>
                        </td>
                    <% end %>
                  </tr>
              <% end %>
           <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
<script src="../../assets/js/vendor/holder.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<!--script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

app/views/users/manage.html.erb
<head lang="en" ng-app="ctrpApp">
  <meta charset="UTF-8">
  <title>CTRP</title>
</head>
<body>
<div>
  <img src="/ctrp/static/images/NIH-red-logo.png"/> <b>National Cancer Institute | Clinical Trials Reporting Program</b>
</div>

<div>
  <h3>User Management Links</h3>
  <ul>
    <% if local_user_signed_in? %>
        <b>Current Local User is <%= current_local_user.username %></b><br/>
        <li><%= link_to 'Edit User Account', edit_local_user_registration_path %></li>
    <% end %>
    <% if ldap_user_signed_in? %>
        <b>Current ldap User is <%= current_ldap_user.username %></b><br/>
    <% end %>
    <li><a href="/ctrp/users">List Users</a></li>
    <li><a href="/ctrp/sign_in">Sign In</a></li>
    <li><a href="/ctrp/local_users/sign_up">Sign Up</a></li>
    <li><%= link_to 'Sign out', destroy_session_path, method: :delete %></li>

  </ul>
</div>


</body>
</html>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>