config/routes.rb
Rails.application.routes.draw do

  resources :trial_versions

  resources :accrual_disease_terms

  resources :trial_documents

  scope "/ctrp" do

    namespace "ws" do
      scope '/api' do
        scope '/v1' do
          scope '/trials' do
            scope '/complete' do
              get '/' => 'api_trials#index'
              get '/:id' =>  'api_trials#show'
              post '/' => 'api_trials#create'
              post '/:idType/:id' => 'api_trials#update'
              post '/:id' => 'api_trials#update'
              put '/:idType/:id' => 'api_trials#amend'
              put  '/:id' =>  'api_trials#update'
              put  '/:id/status' =>  'api_trials#change_status'
            end
          end
        end
      end
    end

    devise_for :users
    root 'ctrp#index'

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    get '/ctrp/', :to => redirect('/index.html')
    resources :organizations do
      collection do
        get 'search'
        post 'search'
        post 'select'
        post 'curate'
        post 'unique', defaults: {format: 'json'}
      end
    end

    resources :source_statuses

    resources :source_contexts

    resources :families do
      collection do
            get 'search'
            post 'search'
            post 'unique', defaults: {format: 'json'}
          end
    end

    resources :families do
      member do
        get  'get_orgs'
      end
      end

    scope '/familystuff' do

      resources :family_statuses, :family_types, :family_relationships, :family_memberships

    end

    resources :family_statuses

    resources :family_types

    resources :family_relationships

    resources :family_memberships

    resources :pa_trials
    get '/pa/trial/:trial_id/checkout/:type', to: 'trials#checkout_trial'
    get '/pa/trial/:trial_id/checkin/:type', to: 'trials#checkin_trial'

    resources :comments
    get '/instance/:uuid/comments/count(/:field)', to: 'comments#count'
    get '/instance/:uuid/comments(/:field)', to: 'comments#comments_for_instance'

    get '/users/search' => 'users#search'
    get '/users/gsa' => 'users#gsa'
    post '/users/search' => 'users#search'
    resources :users, param: :username do
      member do
        post 'approve'
        post 'disapprove'
      end
    end

    resources :people do
      collection do
        get 'search'
        post 'search'
        post 'curate'
        post 'unique', defaults: {format: 'json'}
      end
    end

    resources :trial_versions do
      collection do
        get 'index'
        post 'history'
      end
    end

    resources :po_affiliations
    resources :po_affiliation_statuses

    get '/countries' => 'util#get_countries'
    get '/states' => 'util#get_states'
    get '/backoffice' => 'backoffice#index'
    get '/backoffice/download_log'
    get '/backoffice/static_members'

    get '/dmzutils/app_version' => 'dmz_utils#get_app_version'
    get '/dmzutils/app_rel_milestone' => 'dmz_utils#get_app_rel_milestone'
    get '/dmzutils/login_bulletin' => 'dmz_utils#get_login_bulletin'
    get '/dmzutils/git_info' => 'dmz_utils#get_git_info'

    devise_scope :user do
      delete "sign_out" => "sessions#destroyrailslogin", :as => :destroyrailslogin_session
    end

    devise_for :ldap_users, :local_users, skip: [ :sessions ]
    devise_for :omniauth_users, :controllers => { :omniauth_callbacks => "omniauth_users/omniauth_callbacks" }
    devise_scope :local_user do
      get 'sign_in' => 'sessions#new', :as => :new_session
      post 'sign_in' => 'sessions#create', :as => :create_session
      post 'sign_out' => 'sessions#destroy', :as => :destroy_session
      post 'sign_up' => 'registrations#create', :as => :create_registration
      get 'change_password' => 'registrations#edit', :as => :edit_registration
      post 'change_password' => 'registrations#update', :as => :update_registration
    end

    scope '/pa' do
      get 'nih_nci_div_pa' => 'util#get_nih_nci_div_pa'
      get 'nih_nci_prog_pa' => 'util#get_nih_nci_prog_pa'
      get 'trial_document_types' => 'util#trial_document_types'
      resources :submission_methods
    end

    scope '/registry' do
      resources :study_sources
      resources :phases
      resources :primary_purposes
      resources :secondary_purposes
      resources :accrual_disease_terms
      resources :responsible_parties
      resources :trials do
        collection do
          get  'search'
          post 'search'
          get  'search_pa'
          post 'search_pa'
          post 'validate_status'
          get  'get_grants_serialnumber'
          post 'get_grants_serialnumber'
          get  'get_central_contact_types'
          get  'search_clinical_trials_gov'
          post 'import_clinical_trials_gov'
          get  'get_board_approval_statuses'
        end
      end

      resources :protocol_id_origins
      resources :holder_types
      resources :expanded_access_types
      resources :trial_statuses
      resources :processing_statuses
      resources :milestones
      resources :research_categories
      resources :site_recruitment_statuses
      resources :participating_sites do
        collection do
          post 'validate_status'
        end
      end
      resources :site_rec_status_wrappers
      resources :trial_documents do
        collection do
          get 'download/:id' => 'trial_documents#download'
        end
      end

      get 'funding_mechanisms' => 'util#get_funding_mechanisms'
      get 'institute_codes' => 'util#get_institute_codes'
      get 'nci' => 'util#get_nci'
      get 'nih' => 'util#get_nih'

      get 'accepted_file_types' => 'util#get_accepted_file_types'
    end
  end

end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_filter :wrapper_authenticate_user unless Rails.env.test?
  rescue_from CanCan::AccessDenied do |exception|
    Rails.logger.debug "Access denied on #{exception.action} #{exception.subject.inspect}"
    redirect_to users_path, :alert => exception.message
  end

  def index
    authorize! :access_backoffice, :manage_backoffice
  end

  def static_members
    authorize! :access_backoffice, :manage_backoffice
  end

  def download_log
    authorize! :access_backoffice, :manage_backoffice
    send_file(
        "#{Rails.root}/../../logs/#{Rails.env}.log",
        filename: "#{Rails.env}.log",
        type: "text/plain"
    )
  end
end

app/views/backoffice/index.erb
<html>
<head>
  <meta charset="UTF-8">
  <title>CTRP Backoffice</title>
</head>
<body>


    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-2">
                <h4>CTRP Backoffice</h4>
                <ul class="nav nav-stacked">
                    <li><a href="/ctrp/ui#/main/welcome">Back to Angular</a></li>
                </ul>
                <h4>CTRP App Administration</h4>
                <ul class="nav nav-stacked">
                    <li><a href="/ctrp/admin">Rails Admin Plugin</a></li>
                    <li><a href="/ctrp/admin/app_setting">App Settings</a></li>
                    <li><a href="/ctrp/backoffice/static_members">Static Members</a></li>
                    <li><a href="/ctrp/users">Rails User Portal</a></li>
                </ul>
                <h4>App Debugging</h4>
                <ul class="nav nav-stacked">
                    <li><%= link_to 'Download Rails application log', backoffice_download_log_url %></li>
                </ul>
            </div>
            <div class="col-sm-9 col-md-10">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title">Rails Environment</div>
                    </div>
                    <div class="panel-body">
                        <ul>
                            <li class="pad-text gray-text">Rails environment: <%= Rails.env%></li>
                            <li class="pad-text gray-text">Git information:
                                <ul>
                                    <li class="pad-text gray-text">Branch: <%=CTRP::GIT_BRANCH %></li>
                                    <li class="pad-text gray-text">Short revision: <%=CTRP::GIT_SHORT_REVISION %></li>
                                    <li class="pad-text gray-text">Full revision:
                                        <ul>
                                            <li><a target="_blank" href="https://github.com/cbiit/ctrp/commit/<%=CTRP::GIT_FULL_REVISION %>"><%=CTRP::GIT_FULL_REVISION %></a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        </ul>

                        Rails ENV dump:<br />
                            <%= debug ENV.to_h.to_yaml %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

app/views/backoffice/static_members.erb
<head lang="en" ng-app="ctrpApp">
  <meta charset="UTF-8">
  <title>CTRP Static Members</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="/ctrp/ui/css/override.css">

  <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.0/angular.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.15/angular-ui-router.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.0/angular-resource.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.0/angular-animate.min.js"></script>


  <!-- angular modules/dependencies from third parties -->
  <script src="third_party_libs/angular-local-storage.js"></script>

</head>
<body>
<div>
  <img src="/ctrp/static/images/NIH-red-logo.png"/> <b>National Cancer Institute | Clinical Trials Reporting Program</b>
</div>
<h3>CTRP Static Members</h3>

<div>
  <ul>
    <li><a href="/ctrp/backoffice">Backoffice</a></li>
    <li><a href="/ctrp/admin/family_relationship">Family Relationsip</a></li>
    <li><a href="/ctrp/admin/family_status">Family Status</a></li>
    <li><a href="/ctrp/admin/family_type">Family Type</a></li>
    <li><a href="/ctrp/admin/po_affiliation_status">Person Org Affiliation Status</a></li>
    <li><a href="/ctrp/admin/source_context">Source Context</a></li>
    <li><a href="/ctrp/admin/source_status">Source Status</a></li>
    <li><a href="/ctrp/admin/internal_source">Internal Source</a></li>
  </ul>
</div>


</body>
</html>