config/routes.rb
Rails.application.routes.draw do

  resources :trial_versions

  resources :accrual_disease_terms

  resources :trial_documents

  scope "/ctrp" do

    namespace "ws" do
      scope '/api' do
        scope '/v1' do
          scope '/trials' do
            scope '/complete' do
              get '/' => 'api_trials#index'
              get '/:id' =>  'api_trials#show'
              post '/' => 'api_trials#create'
              post '/:idType/:id' => 'api_trials#update'
              post '/:id' => 'api_trials#update'
              put '/:idType/:id' => 'api_trials#amend'
              put  '/:id' =>  'api_trials#update'
              put  '/:id/status' =>  'api_trials#change_status'
            end
          end
        end
      end
    end

    devise_for :users
    root 'ctrp#index'

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    get '/ctrp/', :to => redirect('/index.html')
    resources :organizations do
      collection do
        get 'search'
        post 'search'
        post 'select'
        post 'curate'
        post 'unique', defaults: {format: 'json'}
      end
    end

    resources :source_statuses

    resources :source_contexts

    resources :families do
      collection do
            get 'search'
            post 'search'
            post 'unique', defaults: {format: 'json'}
          end
    end

    resources :families do
      member do
        get  'get_orgs'
      end
      end

    scope '/familystuff' do

      resources :family_statuses, :family_types, :family_relationships, :family_memberships

    end

    resources :family_statuses

    resources :family_types

    resources :family_relationships

    resources :family_memberships

    resources :pa_trials
    get '/pa/trial/:trial_id/checkout/:type', to: 'trials#checkout_trial'
    get '/pa/trial/:trial_id/checkin/:type', to: 'trials#checkin_trial'

    resources :comments
    get '/instance/:uuid/comments/count(/:field)', to: 'comments#count'
    get '/instance/:uuid/comments(/:field)', to: 'comments#comments_for_instance'

    get '/users/search' => 'users#search'
    get '/users/gsa' => 'users#gsa'
    post '/users/search' => 'users#search'
    resources :users, param: :username do
      member do
        post 'approve'
        post 'disapprove'
      end
    end

    resources :people do
      collection do
        get 'search'
        post 'search'
        post 'curate'
        post 'unique', defaults: {format: 'json'}
      end
    end

    resources :trial_versions do
      collection do
        get 'index'
        post 'history'
      end
    end

    resources :po_affiliations
    resources :po_affiliation_statuses

    get '/countries' => 'util#get_countries'
    get '/states' => 'util#get_states'
    get '/backoffice' => 'backoffice#index'
    get '/backoffice/download_log'
    get '/backoffice/static_members'

    get '/dmzutils/app_version' => 'dmz_utils#get_app_version'
    get '/dmzutils/app_rel_milestone' => 'dmz_utils#get_app_rel_milestone'
    get '/dmzutils/login_bulletin' => 'dmz_utils#get_login_bulletin'
    get '/dmzutils/git_info' => 'dmz_utils#get_git_info'

    devise_scope :user do
      delete "sign_out" => "sessions#destroyrailslogin", :as => :destroyrailslogin_session
    end

    devise_for :ldap_users, :local_users, skip: [ :sessions ]
    devise_for :omniauth_users, :controllers => { :omniauth_callbacks => "omniauth_users/omniauth_callbacks" }
    devise_scope :local_user do
      get 'sign_in' => 'sessions#new', :as => :new_session
      post 'sign_in' => 'sessions#create', :as => :create_session
      post 'sign_out' => 'sessions#destroy', :as => :destroy_session
      post 'sign_up' => 'registrations#create', :as => :create_registration
      get 'change_password' => 'registrations#edit', :as => :edit_registration
      post 'change_password' => 'registrations#update', :as => :update_registration
    end

    scope '/pa' do
      get 'nih_nci_div_pa' => 'util#get_nih_nci_div_pa'
      get 'nih_nci_prog_pa' => 'util#get_nih_nci_prog_pa'
      get 'trial_document_types' => 'util#trial_document_types'
      resources :submission_methods
    end

    scope '/registry' do
      resources :study_sources
      resources :phases
      resources :primary_purposes
      resources :secondary_purposes
      resources :accrual_disease_terms
      resources :responsible_parties
      resources :trials do
        collection do
          get  'search'
          post 'search'
          get  'search_pa'
          post 'search_pa'
          post 'validate_status'
          get  'get_grants_serialnumber'
          post 'get_grants_serialnumber'
          get  'get_central_contact_types'
          get  'search_clinical_trials_gov'
          post 'import_clinical_trials_gov'
          get  'get_board_approval_statuses'
        end
      end

      resources :protocol_id_origins
      resources :holder_types
      resources :expanded_access_types
      resources :trial_statuses
      resources :processing_statuses
      resources :milestones
      resources :research_categories
      resources :site_recruitment_statuses
      resources :participating_sites do
        collection do
          post 'validate_status'
        end
      end
      resources :site_rec_status_wrappers
      resources :trial_documents do
        collection do
          get 'download/:id' => 'trial_documents#download'
        end
      end

      get 'funding_mechanisms' => 'util#get_funding_mechanisms'
      get 'institute_codes' => 'util#get_institute_codes'
      get 'nci' => 'util#get_nci'
      get 'nih' => 'util#get_nih'

      get 'accepted_file_types' => 'util#get_accepted_file_types'
    end
  end

end

app/models/version.rb
# == Schema Information
#
# Table name: versions
#
#  id             :integer          not null, primary key
#  item_type      :string           not null
#  item_id        :integer          not null
#  event          :string           not null
#  whodunnit      :string
#  object         :text
#  created_at     :datetime
#  object_changes :text
#
# Indexes
#
#  index_versions_on_item_type_and_item_id  (item_type,item_id)
#

class Version < ActiveRecord::Base
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :set_version, only: [:show, :edit, :update, :destroy]

  def diff
  end

  # GET /versions
  # GET /versions.json
  def index
    #@data_tables = ActiveRecord::Base.connection.tables
    #@model_options = @data_tables.map{|u| [ u ] }
    @data_tables =Version.find_by_sql("select distinct item_type from versions");
    print @data_tables
    @versions = Version.find_by_sql("select distinct item_id,item_type from versions order by item_type");

  end

  # GET /versions/1
  # GET /versions/1.json
  def show
  end

  # DELETE /versions/1
  # DELETE /versions/1.json
  def destroy
    @version.destroy
    respond_to do |format|
      format.html { redirect_to versions_url, notice: 'Version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def history
    p params
    @datas =Version.where("item_type = ? AND item_id = ? ", params[:item_type],params[:item_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_version
      @version = Version.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def version_params
      params[:version]
    end
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/versions/_form.html.erb
<%= form_for(@version) do |f| %>
  <% if @version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@version.errors.count, "error") %> prohibited this version from being saved:</h2>

      <ul>
      <% @version.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/versions/edit.html.erb
<h1>Editing Version</h1>

<%= render 'form' %>

<%= link_to 'Show', @version %> |
<%= link_to 'Back', versions_path %>

app/views/versions/history.html.erb
<h2>Previous Versions</h2>


      <div class="container">
        <h1>History</h1>

        <ul>
          <% @datas.each do |version| %>
              <li>
                <%= l(version.created_at, format: "%-d.%m.%Y %H:%M:%S %Z") %><br/>
                Event ID: <%= version.id %><br/>
                <b>Target:</b> <%= version.item_type %>
                <small>(id: <%= version.item_id %>)</small><br>
                <b>action</b> <%= version.event %>;<br/>
                <div>
                  Changeset:
                  <pre><%= version.object_changes %></pre>
                </div>
              </li>
          <% end %>
        </ul>
      </div>

app/views/versions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Versions</h1>


<select name="user_id">
  <%= @data_tables.each do |dt| %>
      <option value="<%= dt.item_type %>"><%= dt.item_type %></option>
  <% end %>
</select>
<br>
<table>
  <thead>
    <tr>
      <th colspan="1">Item Type</th>
      <th colspan="1">Item Id</th>
      <th colspan="1">Event</th>
      <th colspan="1">Whodunnit</th>
      <th colspan="1">Createa At</th>
    </tr>
  </thead>

  <tbody>
    <% @versions.each do |version| %>
      <tr>
        <td><%= link_to version.item_type, :action => 'history', :item_type => version.item_type, :item_id => version.item_id %></td>
        <td><%= version.item_id %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/versions/new.html.erb
<h1>New Version</h1>

<%= render 'form' %>

<%= link_to 'Back', versions_path %>

app/views/versions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_version_path(@version) %> |
<%= link_to 'Back', versions_path %>