config/routes.rb
Rails.application.routes.draw do

  resources :trial_versions

  resources :accrual_disease_terms

  resources :trial_documents

  scope "/ctrp" do

    namespace "ws" do
      scope '/api' do
        scope '/v1' do
          scope '/trials' do
            scope '/complete' do
              get '/' => 'api_trials#index'
              get '/:id' =>  'api_trials#show'
              post '/' => 'api_trials#create'
              post '/:idType/:id' => 'api_trials#update'
              post '/:id' => 'api_trials#update'
              put '/:idType/:id' => 'api_trials#amend'
              put  '/:id' =>  'api_trials#update'
              put  '/:id/status' =>  'api_trials#change_status'
            end
          end
        end
      end
    end

    devise_for :users
    root 'ctrp#index'

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    get '/ctrp/', :to => redirect('/index.html')
    resources :organizations do
      collection do
        get 'search'
        post 'search'
        post 'select'
        post 'curate'
        post 'unique', defaults: {format: 'json'}
      end
    end

    resources :source_statuses

    resources :source_contexts

    resources :families do
      collection do
            get 'search'
            post 'search'
            post 'unique', defaults: {format: 'json'}
          end
    end

    resources :families do
      member do
        get  'get_orgs'
      end
      end

    scope '/familystuff' do

      resources :family_statuses, :family_types, :family_relationships, :family_memberships

    end

    resources :family_statuses

    resources :family_types

    resources :family_relationships

    resources :family_memberships

    resources :pa_trials
    get '/pa/trial/:trial_id/checkout/:type', to: 'trials#checkout_trial'
    get '/pa/trial/:trial_id/checkin/:type', to: 'trials#checkin_trial'

    resources :comments
    get '/instance/:uuid/comments/count(/:field)', to: 'comments#count'
    get '/instance/:uuid/comments(/:field)', to: 'comments#comments_for_instance'

    get '/users/search' => 'users#search'
    get '/users/gsa' => 'users#gsa'
    post '/users/search' => 'users#search'
    resources :users, param: :username do
      member do
        post 'approve'
        post 'disapprove'
      end
    end

    resources :people do
      collection do
        get 'search'
        post 'search'
        post 'curate'
        post 'unique', defaults: {format: 'json'}
      end
    end

    resources :trial_versions do
      collection do
        get 'index'
        post 'history'
      end
    end

    resources :po_affiliations
    resources :po_affiliation_statuses

    get '/countries' => 'util#get_countries'
    get '/states' => 'util#get_states'
    get '/backoffice' => 'backoffice#index'
    get '/backoffice/download_log'
    get '/backoffice/static_members'

    get '/dmzutils/app_version' => 'dmz_utils#get_app_version'
    get '/dmzutils/app_rel_milestone' => 'dmz_utils#get_app_rel_milestone'
    get '/dmzutils/login_bulletin' => 'dmz_utils#get_login_bulletin'
    get '/dmzutils/git_info' => 'dmz_utils#get_git_info'

    devise_scope :user do
      delete "sign_out" => "sessions#destroyrailslogin", :as => :destroyrailslogin_session
    end

    devise_for :ldap_users, :local_users, skip: [ :sessions ]
    devise_for :omniauth_users, :controllers => { :omniauth_callbacks => "omniauth_users/omniauth_callbacks" }
    devise_scope :local_user do
      get 'sign_in' => 'sessions#new', :as => :new_session
      post 'sign_in' => 'sessions#create', :as => :create_session
      post 'sign_out' => 'sessions#destroy', :as => :destroy_session
      post 'sign_up' => 'registrations#create', :as => :create_registration
      get 'change_password' => 'registrations#edit', :as => :edit_registration
      post 'change_password' => 'registrations#update', :as => :update_registration
    end

    scope '/pa' do
      get 'nih_nci_div_pa' => 'util#get_nih_nci_div_pa'
      get 'nih_nci_prog_pa' => 'util#get_nih_nci_prog_pa'
      get 'trial_document_types' => 'util#trial_document_types'
      resources :submission_methods
    end

    scope '/registry' do
      resources :study_sources
      resources :phases
      resources :primary_purposes
      resources :secondary_purposes
      resources :accrual_disease_terms
      resources :responsible_parties
      resources :trials do
        collection do
          get  'search'
          post 'search'
          get  'search_pa'
          post 'search_pa'
          post 'validate_status'
          get  'get_grants_serialnumber'
          post 'get_grants_serialnumber'
          get  'get_central_contact_types'
          get  'search_clinical_trials_gov'
          post 'import_clinical_trials_gov'
          get  'get_board_approval_statuses'
        end
      end

      resources :protocol_id_origins
      resources :holder_types
      resources :expanded_access_types
      resources :trial_statuses
      resources :processing_statuses
      resources :milestones
      resources :research_categories
      resources :site_recruitment_statuses
      resources :participating_sites do
        collection do
          post 'validate_status'
        end
      end
      resources :site_rec_status_wrappers
      resources :trial_documents do
        collection do
          get 'download/:id' => 'trial_documents#download'
        end
      end

      get 'funding_mechanisms' => 'util#get_funding_mechanisms'
      get 'institute_codes' => 'util#get_institute_codes'
      get 'nci' => 'util#get_nci'
      get 'nih' => 'util#get_nih'

      get 'accepted_file_types' => 'util#get_accepted_file_types'
    end
  end

end

app/helpers/after_signup_helper.rb
module AfterSignupHelper
end

app/views/after_signup/add_organization.html.erb
<%= form_for(@user, :url => wizard_path, :method => :put) do |f| %>
    <%= f.text_field :street_address, :placeholder => 'street_address' %>
    <%= f.submit 'Next', :class => 'btn btn-primary' %>
<% end %>


<%= link_to 'skip', next_wizard_path %>

app/views/after_signup/add_questions.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">

  <title>CTRP User Portal</title>

  <!-- Bootstrap core CSS -->
  <!--link href="../..//css/bootstrap.min.css" rel="stylesheet"-->

  <!-- Custom styles for this template -->
  <link href="../../assets/stylesheets/dashboard.scss" rel="stylesheet">

  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
  <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">CTRP User Portal</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">


        <% if local_user_signed_in? %><li><a class="navbar-brand" href="#">Current Local User is <%= current_local_user.username %></a><li/> <% end %>
        <% if local_user_signed_in? %>
            <li><%= link_to 'Sign out', destroy_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
        <br/><br/>
        <li><a href="/ctrp/ui#/main/sign_in">CTRP Main</a></li>
        <% if local_user_signed_in? ||  ldap_user_signed_in? %>
            <li><%= link_to "List Users", users_path %></li>
            <li><%= link_to "Assign Organization", search_organizations_path %></li>
            <% if current_local_user.role == "ROLE_SUPER" %>
                <li><%= link_to "BackOffice", backoffice_path %></li>
            <% end %>
            <!--li><!--%= link_to 'Edit User ', edit_user_path(current_local_user.username) %></li-->
        <% end %>
        <% if !local_user_signed_in? &&  !ldap_user_signed_in? %>
            <li><%= link_to "Sign In", new_session_path %></li>
        <% end %>
        <li><a href="/ctrp/local_users/sign_up">Sign Up</a></li>
        <% if local_user_signed_in? %>
            <!--li><!--%= link_to "Change your password", edit_local_user_registration_path %></li-->
        <% end %>
      </ul>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

      <h2>Thanks for signing up </h2>

      <h3> Receive Email Notifications </h3>

      <%= form_for(@user, :url => wizard_path, :method => :put) do |f| %>
          <div class="field">
            <%= f.label :receive_email_notifications %><br />
            <%= f.label :receive_email_notifications, "Yes", :value => "true"  %>
            <%= f.radio_button :receive_email_notifications, true %>
            <%= f.label :receive_email_notifications, "No", :value => "false" %>
            <%= f.radio_button :receive_email_notifications, false, :checked => true %>
          </div>
          <div class="field">
            <%= f.submit 'Save', :class => 'btn btn-primary' %>
          </div>

      <% end %>

      <%= link_to 'Back to User Portal', users_path %>



    </div>
  </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
<script src="../../assets/js/vendor/holder.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<!--script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

app/views/after_signup/add_user_details.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">

  <title>CTRP User Portal</title>

  <!-- Bootstrap core CSS -->
  <!--link href="../..//css/bootstrap.min.css" rel="stylesheet"-->

  <!-- Custom styles for this template -->
  <link href="../../assets/stylesheets/dashboard.scss" rel="stylesheet">

  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
  <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">CTRP User Portal</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">


        <% if local_user_signed_in? %><li><a class="navbar-brand" href="#">Current Local User is <%= current_local_user.username %></a><li/> <% end %>
        <% if local_user_signed_in? %>
            <li><%= link_to 'Sign out', destroy_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
        <br/><br/>
        <li><a href="/ctrp/ui#/main/sign_in">CTRP Main</a></li>
        <% if local_user_signed_in? ||  ldap_user_signed_in? %>
            <li><%= link_to "List Users", users_path %></li>
            <li><%= link_to "Assign Organization", search_organizations_path %></li>
            <% if current_local_user.role == "ROLE_SUPER" %>
                <li><%= link_to "BackOffice", backoffice_path %></li>
            <% end %>
            <!--li><!--%= link_to 'Edit User ', edit_user_path(current_local_user.username) %></li-->
        <% end %>
        <% if !local_user_signed_in? &&  !ldap_user_signed_in? %>
            <li><%= link_to "Sign In", new_session_path %></li>
        <% end %>
        <li><a href="/ctrp/local_users/sign_up">Sign Up</a></li>
        <% if local_user_signed_in? %>
            <!--li><!--%= link_to "Change your password", edit_local_user_registration_path %></li-->
        <% end %>
      </ul>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

      <div class="table-responsive"> 
        <h2>Thanks for signing up </h2>

        <h3> User Details </h3>
        <%= form_for(@user, :url => wizard_path, :method => :put) do |f| %>
            <div class="field">
              <%= label_tag(:first_name, "First Name:") %>
              <%= f.text_field :first_name, :placeholder => 'first_name' %>
            </div>
            <div class="field">
              <%= label_tag(:last_name, "Last Name:") %>
              <%= f.text_field :last_name, :placeholder => 'Last name' %>
            </div>
            <div class="field">
              <%= label_tag(:middle_name, "Middle Name:") %>
              <%= f.text_field :middle_name, :placeholder => 'Middle name' %>
            </div>
            <div class="field">
              <%= label_tag(:street_address, "Street Address:") %>
              <%= f.text_field :street_address, :placeholder => 'street address' %>
            </div>
            <div class="field">
              <%= label_tag(:zipcode, "zipcode:") %>
              <%= f.text_field :zipcode, :placeholder => 'zip code' %>
            </div>
            <div class="field">
              <%= f.submit 'Next', :class => 'btn btn-primary' %>
            </div>
        <% end %>

        <%= link_to 'Skip this page', next_wizard_path %>

      </div>  

    </div>
  </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
<script src="../../assets/js/vendor/holder.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<!--script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>